### ISSUE TITLE
inconsistent plotting backend between examples and this package

### ISSUE THREAD

**Issue by Roger-luo** [QuEraComputing/bloqade-python#875]
our notebook example uses matplotlib https://queracomputing.github.io/bloqade-python-examples/latest/examples/example-1-rabi/#introduction

but our default plotting backend is bokeh. We need to pick one. If we are giving up on adding more interactive features in bloqade, we should switch back to matplotlib from bokeh and make sure there is a good default behaviour.

**Comment by weinbe58** [comment]
So there are two things here:

1. We had decided to provide Bokeh based plots for visualizing **_Bloqade_** objects only. The plots you refer to are using data extracted from Bloqade objects and then doing some other stuff with that data to make some plots in a way that is unrelated to the original Bloqade Objects. 
2. The choice to use matplotlib was more because Bokeh adds a bunch of extra boiler plate code that distracts from the main message of the tutorial which is running simulation and hardware and doing a basic comparison of the results. John had written the plots in Bokeh but it nearly doubled the amount of code required to make the plots and since matplotlib is a pretty common library for our audience we felt using that was a better idea then making a Bokeh plot with all the interactive features which doesn't add much to the message.
